services:
  mongo_db:
    image: mongo:latest
    container_name: library_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: books
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: library_redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: library_api
    environment:
      MONGODB_URL: mongodb://mongo_admin:password@mongo_db:27017
      MONGODB_DB: books
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
      - redis

volumes:
  mongo_data: